#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "perf-glance @ git+https://github.com/vzaliva/perf-glance.git",
# ]
# ///

"""Launch perf-glance via uv. Run with: ./perf-glance [args]"""

from perf_glance import main

if __name__ == "__main__":
    main()
